### ISSUE TITLE
cameraRoll error on expo sdk 40

### ISSUE THREAD

**Issue by goodatech** [MonstroDev/expo-image-picker-multiple#30] opened 2020-12-26 19:16 UTC
Looks like permissions have changed in expo sdk 40 and MEDIA_LIBRARY is the new one

**Comment by gregfenton** [comment] 2020-12-27 18:52
More details about [this change to the API](https://github.com/expo/expo/pull/10643).  I'm surprised not to find mention of this in [the SDK 40 release notes](https://github.com/expo/expo/blob/master/CHANGELOG.md#4000--2020-11-17) (or I'm just missing it...)

**Comment by KemaneWright** [comment] 2020-12-31 08:48
Sorry meant to put my first comment here. I'm trying to get expo-image-picker-multiple working

**Comment by gregfenton** [comment] 2020-12-31 16:41
The fix is to use the new MEDIA_LIBRARY permission, not the CAMERA_ROLL, I believe.

**Comment by ELiHimself** [comment] 2021-01-23 10:08
Does anyone have a fix for this issue yet?

**Comment by KemaneWright** [comment] 2021-01-23 21:11
The problem is the module has its own package.json which uses an old version of Permissions so what I did was go in to node_module/expo-image-picker-multiple/src folder and copy out the two files ImageBrowser and ImageTile into my own components folder, then had to npm install these three

- 'expo-screen-orientation'
- 'expo-media-library'
- 'expo-permissions'

 Made a small modification in my new ImageBrowser file on line 80 in the selectImage() function. 
I changed 
this.props.onChange(newSelected.length, () => this.prepareCallback());
TO
this.props.onChange(newSelected.length, this.prepareCallback());

Then everything worked again

**Comment by KemaneWright** [comment] 2021-01-23 21:12
Obviously not the best or long term solution but I needed a quick solution

**Comment by octagonalsquare** [comment] 2021-01-29 20:14
Is there an actual solution? I'm trying to use this package as I need to select photos on IOS without cropping to a square, but I get 
`[Unhandled promise rejection: Error: Unrecognized permission: cameraRoll, please install and link the package expo-media-library, see more at https://github.com/expo/expo/tree/master/packages/expo-media-library]`

**Comment by MonstroDev** [comment] 2021-03-08 09:28
Package 1.4.0 is released with Expo SDK 40 support.
Sorry for taking so long.

**Closed by MonstroDev** 2021-03-08 09:28 UTC
